### ISSUE TITLE
Bag with `editable: false`

### ISSUE THREAD

**Issue by retyui** [retyui/react-native-confirmation-code-field#45]
> 
Whilst passing editable: false does prevent the cursor from activating, it still seems to clear the code out of the field.

Hopefully this works:
![CodeEditField](https://user-images.githubusercontent.com/13134961/54434850-1437ab00-4727-11e9-8c03-9edb697b1ba2.gif)

_Originally posted by @cjpete in https://github.com/retyui/react-native-confirmation-code-field/issues/35#issuecomment-473287677_

**Comment by retyui** [comment]
@cjpete fixed in 3.2.3

**Comment by cjpete** [comment]
Great - that seems to fix it. Thanks @retyui

**Comment by DwCleb** [comment]
Hello!
I still get this error, my editable props is false but the field clearing happens

**Comment by retyui** [comment]
@DwCleb 
What version do you use?

**Comment by DwCleb** [comment]
@retyui  
"react-native-confirmation-code-field": "^6.4.0"

**Comment by DwCleb** [comment]
When `enable: false` the border bottom color is red.


The Code:
![Screenshot 2020-06-19 at 10 42 05](https://user-images.githubusercontent.com/30187750/85119364-8e53bb00-b219-11ea-9d50-d8043919d6ca.png)

The result:
![codefield](https://user-images.githubusercontent.com/30187750/85119233-59476880-b219-11ea-82f6-045b6468dae0.gif)

**Comment by retyui** [comment]
@DwCleb Try to modify invocing `useClearByFocusCell`

```js
useClearByFocusCell({
    value,
    setValue: (val) => {
       if(ediableEnable){
          setValue(val)
       }
    },
  });
```

**Comment by DwCleb** [comment]
@retyui  Awesome!
Thank you so much!
